### PR TITLE
Add failing test demonstrating #422

### PR DESCRIPTION
**Pull request by koral--**
PR only for bug #422  reproduction purposes. Not for direct merging.

### CODE REVIEW

**Comment by MiSikora** [comment]
It fails for me locally, but I'm confused. Shouldn't this test fail the CI?

**Comment by koral--** [comment]
I expect it to fail on CI. I guess that something is misconfigured on GitHub Actions 🤔 
`test` task is invoked but I'm not sure if unit tests are actually performed.

**Comment by MiSikora** [comment]
Tests seem to run correctly here https://github.com/ChuckerTeam/chucker/pull/424/checks?check_run_id=981509232#step:4:246. Not sure what is going on. Do you test locally on Linux or macOS?

**Comment by koral--** [comment]
On macOS only.

**Comment by vbuberen** [comment]
Just 2 weeks ago I had sort of similar strange issue with Github Actions on another project. Actions just tried to build project without latest commit and I had to do some additional commit to trigger freshly updated build. Happed on a few branches.

**Comment by vbuberen** [comment]
Trying to make Actions show logs to see info about added test.

**Comment by koral--** [comment]
Indeed now it fails.
This Issue is addressed in #427 so it seems that this PR can be closed.

**Pull request closed without merging**
