### PR TITLE
Add TargetApi annotation

### PR DESCRIPTION
**Pull request by Goooler**
## :pencil: Changes

Add `@TargetApi` for `createShortcut()`

### CODE REVIEW

**Comment by vbuberen** [comment]
Thanks for another contribution.

However, I am not sure what is the advantage of having this annotation? I haven't seen any lint warnings so far about this function.

**Comment by cortinico** [comment]
Agree to what @vbuberen said

> I haven't seen any lint warnings so far about this function.

I believe that's because the method contains an if-then-else with an API Level check, so that's why Lint is not complaining.

**Comment by Goooler** [comment]
> I believe that's because the method contains an if-then-else with an API Level check, so that's why Lint is not complaining.


`@RequiresApi` will make lint warning, `@TargetApi` will not, add this annotation just for attention.

**Comment by MiSikora** [comment]
[Documentation](https://developer.android.com/reference/android/annotation/TargetApi) does not indicate that usage of this annotation is for attention.

It's for making Lint quiet.

> Indicates that Lint should treat this type as targeting a given API level, no matter what the project target is.

**Comment by vbuberen** [comment]
This brings up to my initial question - why we need this PR? It looks like it won't bring any benefits, so I am closing it.

**Pull request closed without merging**
