### PR TITLE
Refactor ChuckerInterceptor processing internals

### PR DESCRIPTION
**Pull request by MiSikora**
## :page_facing_up: Context

I started working on #523 but it was rather hard to give some public API for custom requests and responses processing.

## :pencil: Changes

There is a lot of code changes but most of it is just refactor. I deleted `IOUtils` class in favour of extensions on `Okio` and `OkHttp`. I also added two classes – `RequestProcessor` and `ResponseProcessor` to remove direct complexity in `ChuckerInterceptor`. These classes do too much ATM anyway but it is some start.

I fixed also some bugs.
- One shot and duplex requests are no longer processed by `ChuckerInterceptor` as it can't do it anyway.
- Plain text response body is no longer incorrectly set when processing requests.
- Requests headers are redacted when processing requests as well. Previously they were only redacted on response received, but this was a potential source of bugs due to exceptions thrown when getting the response.
- Known supported encodings no longer imply that request bodies are plain text. This was false as gzipped body does not necessarily mean plain text.

Some other changes.
- `HttpTransaction` has `isRequestBodyPlainText` and `isResponseBodyPlainText` now set to `false` by default. I feel it is better to rely on explicitly detecting plain text rather than assuming it. The implication is different message in export files for bodies without content.
- IO exceptions handling while processing requests.
- `chucker_body_unexpected_eof` message is removed as it is now impossible to read too much from in-memory buffers while processing the response.

## :no_entry_sign: Breaking

No.

## :hammer_and_wrench: How to test

I added some unit tests for request processing in `ChuckerInterceptor`. You can run the sample and check if everything is fine.

## :stopwatch: Next steps

I'll need to resolve some conflicts after merging #526. Or remove logging changes from this PR if #526 does not get accepted.

### CODE REVIEW

**Comment by cortinico** [comment]
> I fixed also some bugs.
> 
> * One shot and duplex requests are no longer processed by `ChuckerInterceptor` as it can't do it anyway.
> * Plain text response body is no longer incorrectly set when processing requests.
> * Requests headers are redacted when processing requests as well. Previously they were only redacted on response received, but this was a potential source of bugs due to exceptions thrown when getting the response.
> * Known supported encodings no longer imply that request bodies are plain text. This was false as gzipped body does not necessarily mean plain text.

I have to admit that this has been sitting in my Inbox for a month 😅  (I was also pretty busy). Sorry for that.

Could we split this PR out in smaller ones given that is a ~1K LOC diff? Ideally have a refactoring one and others for every PR?

**Comment by vbuberen** [comment]
Joining here (needed some break). Agree with Nico here about splitting the PR for more manageable size.

**Comment by MiSikora** [comment]
I don't think it will shave off much from this PR because most of it is moving internals of `ChuckerInterceptor` to separate classes. But I'll try to split it as best as possible when I find some time.

**Comment by MiSikora** [comment]
Closing this one. I started splitting it into smaller PRs.

**Pull request closed without merging**
