### PR TITLE
Adding util GH actions

### PR DESCRIPTION
**Pull request by cortinico**
## :page_facing_up: Context
I'm adding a couple of util Github Actions. Let's discuss if don't want some of them but I found them more or less useful:

* WIP will hold on a PR if it contains `WIP` in the title
* Automatic Rebase will allow us to rebase a PR by posting `/rebase` in the comment
* Automatic Revert will allow us to revert a commit by posting a `/revert <sha>` of the commit we want to revert.

### CODE REVIEW

**Comment by cortinico** [comment]
> WIP will hold on a PR if it contains WIP in the title

In order for this to work properly we should set status check as required for the protected branches.

**Comment by vbuberen** [comment]
I don't see point in WIP, because Github has draft PRs, which should work fine for us. Moreover, we discussed it already: https://kotlinlang.slack.com/archives/CRWD6370R/p1578055346010400

As to rebase - yeah, might be useful.

As to revert - funny that we also discussed it a few months ago, but I am in for it: https://kotlinlang.slack.com/archives/CRWD6370R/p1583316167015400

**Comment by cortinico** [comment]
> I don't see point in WIP, because Github has draft PRs, which should work fine for us. Moreover, we discussed it already: kotlinlang.slack.com/archives/CRWD6370R/p1578055346010400

Yeah definitely an overlap here. Let's keep it aside for now and merge the other 2.

**Comment by vbuberen** [comment]
The only thing which worries me here is who can use these commands - specifically there is no way to be sure that we will be safe from someone coming to someone'e else PR and do random reverts, for example.

**Comment by cortinico** [comment]
> The only thing which worries me here is who can use these commands - specifically there is no way to be sure that we will be safe from someone coming to someone'e else PR and do random reverts, for example.

Yeah that is possible.

**Comment by vbuberen** [comment]
Let's merge it will the first case of such abuse.

**Pull request merged**
