### PR TITLE
Fixed JSON pretty color printed for long text

### PR DESCRIPTION
**Pull request by kmayoral**
## :camera: Screenshots
Screenshot_20230426_110559

Updated with boolean value color formatting:

Screenshot_20230426_121454

## :page_facing_up: Context
Per this [issue](https://github.com/ChuckerTeam/chucker/issues/1017), I noticed that the current implementation of the JSON color formatting logic would fail to ever complete when presented with a moderately large sized JSON string to format with colors.

## :pencil: Changes
I updated the SpanTextUtil implementation to implement `fun simpleSpanJson(input: CharSequence): SpannableStringBuilder` to match the existing signature of `fun spanJson(input: CharSequence): SpannableStringBuilder`. The difference is that instead of relying on a recursive solution to format the string, we simply process the string token by token which in my tests have allowed for the large json strings to be processed quickly.

## :paperclip: Related PR
N/A

## :no_entry_sign: Breaking
N/A - same method signature

## :hammer_and_wrench: How to test
I had included a unit test with a large string that was failing to complete the test with the old implementation and completing quickly with the new implementation but I removed it due to linting errors for now.

## :stopwatch: Next steps
N/A

### CODE REVIEW

**Comment by kmayoral** [comment]
Here are some screenshots of some local testing I performed when supplying the following long json string to the tests:
https://pokeapi.co/api/v2/pokemon/1/

Screenshot 2023-04-26 at 11 23 03 AM
Screenshot 2023-04-26 at 11 22 59 AM

**Comment by kmayoral** [comment]
I'd also be happy to refactor the changes to remove the old implementation and keep the new one as `spanJson()` if we decide to move forward with this.

**Comment by kmayoral** [comment]
I went ahead a made a few more changes:
- added support for boolean value color formatting
- remove legacy `spanJson()` and renamed this impl to match
- added a single test containing a long json string that failed to complete in the legacy implementation but completes in several seconds with this impl

**Review by cortinico — APPROVED** [review]
Change looks great to me, thanks for adding this @kmayoral

**Comment by kmayoral** [comment]
Happy to help, thanks for a great library!

**Pull request merged**
