### PR TITLE
Add missing fix to changelog

### PR DESCRIPTION
**Pull request by MiSikora**
## :page_facing_up: Context

A bug fix wasn't mentioned in the changelog.

## :pencil: Changes

I updated the changelog.

## :paperclip: Related PR

#538 

## :no_entry_sign: Breaking

No.

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
As a note for the future, we could look into setting up https://danger.systems/kotlin/ to fail PR checks if the changelog file was not updated 🤔

**Comment by MiSikora** [comment]
Do you mean to run it only as a warning and not something that fails CI?

IMO public changelog should be updated only if there are changes affecting users. If Danger requires updates to changelog with every PR I think it would be kind of counterproductive as git log is better suited for this job.

**Comment by cortinico** [comment]
> Do you mean to run it only as a warning and not something that fails CI?

AFAIK it's customisable (as a warn or error)

**Comment by MiSikora** [comment]
Yes, it should be. I used Danger in couple of projects and I really like it. Just wanted to suggest that if we integrate it, then changelog check shouldn't be an error. :)

**Pull request merged**
