### PR TITLE
Enable Explicit Api mode for Chucker

### PR DESCRIPTION
**Pull request by cortinico**
## :page_facing_up: Context

I'm enabling strict explicit API check for Chucker. This will help us make sure we specify visibility of whatever we expose.

This feature is available only on Kotlin 1.4x so we can't merge this at this point.

## :stopwatch: Next steps
We can already address the warning actually. Once we bump to 1.4, we can just enable explicit API and have a green build.

### CODE REVIEW

**Comment by cortinico** [comment]
Here the output of Explicit API:

```
e: Chucker.kt: (9, 1): Visibility must be specified in explicit API mode
e: Chucker.kt: (12, 5): Visibility must be specified in explicit API mode
e: Chucker.kt: (12, 15): Return type must be specified in explicit API mode
e: Chucker.kt: (14, 5): Visibility must be specified in explicit API mode
e: Chucker.kt: (14, 15): Return type must be specified in explicit API mode
e: Chucker.kt: (17, 5): Visibility must be specified in explicit API mode
e: Chucker.kt: (17, 9): Return type must be specified in explicit API mode
e: Chucker.kt: (25, 5): Visibility must be specified in explicit API mode
e: Chucker.kt: (28, 5): Visibility must be specified in explicit API mode
e: Chucker.kt: (31, 5): Visibility must be specified in explicit API mode
e: Chucker.kt: (36, 5): Visibility must be specified in explicit API mode
e: Chucker.kt: (41, 5): Visibility must be specified in explicit API mode
e: ChuckerCollector.kt: (8, 1): Visibility must be specified in explicit API mode
e: ChuckerCollector.kt: (10, 5): Visibility must be specified in explicit API mode
e: ChuckerCollector.kt: (11, 5): Visibility must be specified in explicit API mode
e: ChuckerCollector.kt: (19, 5): Visibility must be specified in explicit API mode
e: ChuckerInterceptor.kt: (11, 1): Visibility must be specified in explicit API mode
e: ChuckerInterceptor.kt: (18, 5): Visibility must be specified in explicit API mode
e: RetentionManager.kt: (8, 1): Visibility must be specified in explicit API mode
e: RetentionManager.kt: (14, 5): Visibility must be specified in explicit API mode
e: RetentionManager.kt: (18, 5): Visibility must be specified in explicit API mode
```

**Comment by vbuberen** [comment]
Promoted this PR from draft just to be able to rebase it to run tests without build matrix and see if everything is fine.

**Comment by vbuberen** [comment]
/rebase

Another attempt to make Github run tests again. Currently there is some issue with workflows not running:
Screenshot 2020-08-19 at 16 37 06

**Comment by vbuberen** [comment]
Resolved conflict with `ChuckerFileProvider()` visibility.
@cortinico Can we merge this PR? Or you plan to do some more changes?

**Comment by cortinico** [comment]
> @cortinico Can we merge this PR? Or you plan to do some more changes?

We can merge it 👌

**Pull request merged**
